// json c++ rpc tests
[
{ "cc_test": {
    "name": "test_runner",
    "cc_sources": [ "*.cpp" ],
    "dependencies": [ "//jsonrpc-cpp:jsonrpc_installed",
                      "//third_party/cppunit:cppunit"
    ],
    "clang": { "cc_compile_args": [ "-Wno-error=self-assign" ] }
} }
] 