// json c++ rpc tests
[
//TODO(cvanarsdale): Get cppunit working... it's autoconf files are too old
//to compile with clang.
//{ "cc_test": {
//    "name": "test_runner",
//    "cc_sources": [ "*.cpp" ],
//    "dependencies": [ "//jsonrpc-cpp:jsonrpc_installed",
//                      "//third_party/cppunit:cppunit"
//    ],
//    "clang": { "cc_compile_args": [ "-Wno-error=self-assign" ] }
//} }
] 