// json c++ rpc tests
[
{ "cc_binary": {
    "name": "test-core",
    "cc_sources": [ "test-core.cpp" ],
    "dependencies": [ "//jsonrpc-cpp:jsonrpc" ]
} },
{ "cc_binary": {
    "name": "test-netstring",
    "cc_sources": [ "test-netstring.cpp" ],
    "dependencies": [ "//jsonrpc-cpp:jsonrpc" ]
} },
{ "cc_binary": {
    "name": "test-runner",
    "cc_sources": [ "test-runner.cpp" ],
    "dependencies": [ "//jsonrpc-cpp:jsonrpc" ]
} },
{ "cc_binary": {
    "name": "test-system",
    "cc_sources": [ "test-system.cpp" ],
    "dependencies": [ "//jsonrpc-cpp:jsonrpc" ]
} }
] 