# Auto-generated by repobuild, do not modify directly.

.gen-obj/src/jsonrpc_client.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_client.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_client.cpp -o .gen-obj/src/jsonrpc_client.cpp.o

.gen-obj/src/jsonrpc_handler.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_handler.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_handler.cpp -o .gen-obj/src/jsonrpc_handler.cpp.o

.gen-obj/src/jsonrpc_httpclient.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_httpclient.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_httpclient.cpp -o .gen-obj/src/jsonrpc_httpclient.cpp.o

.gen-obj/src/jsonrpc_server.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_server.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_server.cpp -o .gen-obj/src/jsonrpc_server.cpp.o

.gen-obj/src/jsonrpc_tcpclient.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_tcpclient.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_tcpclient.cpp -o .gen-obj/src/jsonrpc_tcpclient.cpp.o

.gen-obj/src/jsonrpc_tcpserver.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_tcpserver.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_tcpserver.cpp -o .gen-obj/src/jsonrpc_tcpserver.cpp.o

.gen-obj/src/jsonrpc_udpclient.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_udpclient.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_udpclient.cpp -o .gen-obj/src/jsonrpc_udpclient.cpp.o

.gen-obj/src/jsonrpc_udpserver.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/jsonrpc_udpserver.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/jsonrpc_udpserver.cpp -o .gen-obj/src/jsonrpc_udpserver.cpp.o

.gen-obj/src/netstring.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/netstring.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/netstring.cpp -o .gen-obj/src/netstring.cpp.o

.gen-obj/src/networking.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/networking.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/networking.cpp -o .gen-obj/src/networking.cpp.o

.gen-obj/src/system.cpp.o: .gen-src/jsonrpc-cpp/.dummy jsonrpc.h jsonrpc_client.h jsonrpc_common.h jsonrpc_handler.h jsonrpc_httpclient.h jsonrpc_server.h jsonrpc_tcpclient.h jsonrpc_tcpserver.h jsonrpc_udpclient.h jsonrpc_udpserver.h netstring.h networking.h system.h src/system.cpp
	mkdir -p .gen-obj/src; $(CXX) $(CXXFLAGS) -c -I. -I.gen-files -I.gen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 src/system.cpp -o .gen-obj/src/system.cpp.o

.gen-obj/jsonrpc: .gen-obj/src/jsonrpc_client.cpp.o .gen-obj/src/jsonrpc_handler.cpp.o .gen-obj/src/jsonrpc_httpclient.cpp.o .gen-obj/src/jsonrpc_server.cpp.o .gen-obj/src/jsonrpc_tcpclient.cpp.o .gen-obj/src/jsonrpc_tcpserver.cpp.o .gen-obj/src/jsonrpc_udpclient.cpp.o .gen-obj/src/jsonrpc_udpserver.cpp.o .gen-obj/src/netstring.cpp.o .gen-obj/src/networking.cpp.o .gen-obj/src/system.cpp.o
	$(CXX) $(CXXFLAGS) .gen-obj/src/jsonrpc_client.cpp.o .gen-obj/src/jsonrpc_handler.cpp.o .gen-obj/src/jsonrpc_httpclient.cpp.o .gen-obj/src/jsonrpc_server.cpp.o .gen-obj/src/jsonrpc_tcpclient.cpp.o .gen-obj/src/jsonrpc_tcpserver.cpp.o .gen-obj/src/jsonrpc_udpclient.cpp.o .gen-obj/src/jsonrpc_udpserver.cpp.o .gen-obj/src/netstring.cpp.o .gen-obj/src/networking.cpp.o .gen-obj/src/system.cpp.o -o .gen-obj/jsonrpc -std=c++11 -DUSE_CXX0X -stdlib=libc++ -lpthread -g -O3

jsonrpc: .gen-obj/jsonrpc
	pwd > /dev/null
	ln -f -s .gen-obj/jsonrpc jsonrpc

.gen-src/jsonrpc-cpp:
	mkdir -p .gen-src; if [[ ! -a . ]]; then mkdir -p .; fi; ln -f -s .. .gen-src/jsonrpc-cpp

.gen-src/jsonrpc-cpp/.dummy: .gen-src/jsonrpc-cpp
	if [[ ! -a .gen-src/jsonrpc-cpp/.dummy ]]; then touch .gen-src/jsonrpc-cpp/.dummy; fi

clean:
	rm -f .gen-src/jsonrpc-cpp/.dummy
	rm -f .gen-src/jsonrpc-cpp
	rm -rf .gen-obj
	rm -rf .gen-files
	rm -rf .gen-src

all: jsonrpc

.PHONY: clean all

.DEFAULT_GOAL=all

